/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Logica.Administrador;
import static Logica.BonoSolidario.accesoBD;
import static Logica.BonoSolidario.administrador;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author Diego García
 */
public class AddAdministrador extends javax.swing.JDialog {

    public int tipoOperacion;

    public AddAdministrador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
        tipoOperacion = 0;
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    public int isTipoOperacion() {
        return tipoOperacion;
    }

    public void setTipoOperacion(int tipoOperacion) {
        this.tipoOperacion = tipoOperacion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPNuevoAdmin = new javax.swing.JPanel();
        JLNombre = new javax.swing.JLabel();
        JLCedula = new javax.swing.JLabel();
        JLUsuario = new javax.swing.JLabel();
        JLPass = new javax.swing.JLabel();
        JLConfiPass = new javax.swing.JLabel();
        JTxFNombre = new javax.swing.JTextField();
        JTxFCedula = new javax.swing.JTextField();
        JTxFUsuario = new javax.swing.JTextField();
        JTxFPass = new javax.swing.JPasswordField();
        JTxFConfiPass = new javax.swing.JPasswordField();
        JPSU = new javax.swing.JPanel();
        JLSUUsuario = new javax.swing.JLabel();
        JTxFSUUsuario = new javax.swing.JTextField();
        JLSUPass = new javax.swing.JLabel();
        JTxFSUPass = new javax.swing.JPasswordField();
        JBAceptar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JPNuevoAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JLNombre.setText("Nombre:");

        JLCedula.setText("Cédula:");

        JLUsuario.setText("Usuario:");

        JLPass.setText("Password:");

        JLConfiPass.setText("Confirmar password:");

        JTxFNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxFNombreKeyTyped(evt);
            }
        });

        JTxFCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxFCedulaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout JPNuevoAdminLayout = new javax.swing.GroupLayout(JPNuevoAdmin);
        JPNuevoAdmin.setLayout(JPNuevoAdminLayout);
        JPNuevoAdminLayout.setHorizontalGroup(
            JPNuevoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNuevoAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPNuevoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLConfiPass, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPNuevoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTxFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPNuevoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JTxFConfiPass, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JTxFPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addComponent(JTxFUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JTxFCedula, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPNuevoAdminLayout.setVerticalGroup(
            JPNuevoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNuevoAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPNuevoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNombre)
                    .addComponent(JTxFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPNuevoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLCedula)
                    .addComponent(JTxFCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPNuevoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLUsuario)
                    .addComponent(JTxFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPNuevoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLPass)
                    .addComponent(JTxFPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPNuevoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLConfiPass)
                    .addComponent(JTxFConfiPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPSU.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Super Usuario"));

        JLSUUsuario.setText("Usuario:");

        JLSUPass.setText("Password:");

        javax.swing.GroupLayout JPSULayout = new javax.swing.GroupLayout(JPSU);
        JPSU.setLayout(JPSULayout);
        JPSULayout.setHorizontalGroup(
            JPSULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPSULayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPSULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLSUUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTxFSUUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(JPSULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPSULayout.createSequentialGroup()
                        .addComponent(JLSUPass, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addComponent(JTxFSUPass))
                .addContainerGap())
        );
        JPSULayout.setVerticalGroup(
            JPSULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPSULayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPSULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLSUUsuario)
                    .addComponent(JLSUPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPSULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTxFSUUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTxFSUPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JBAceptar.setText("Aceptar");
        JBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAceptarActionPerformed(evt);
            }
        });

        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JPNuevoAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPSU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPNuevoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPSU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBAceptar)
                    .addComponent(JBCancelar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAceptarActionPerformed
        if (JTxFPass.getText().equals(JTxFConfiPass.getText())) {
            //if (BonoSolidario.accesoBD.consultaAdmin(JTxFSUUsuario.getText(), JTxFSUPass.getText(), false)) {

            String password = DigestUtils.md5Hex(JTxFSUPass.getText());

            if (administrador.getTipo() == 1 && administrador.getUsuario().equals(JTxFSUUsuario.getText()) && administrador.getPass().equals(password)) {

                password = DigestUtils.md5Hex(JTxFPass.getText());
                Administrador admin = new Administrador(JTxFNombre.getText(), Long.parseLong(JTxFCedula.getText()), password, JTxFUsuario.getText(), 0);
                boolean exito = true;
                String mensaje = "";

                switch (tipoOperacion) {
                    case 1:
                        if (vacio(JPSU) || vacio(JPNuevoAdmin)) {
                            JOptionPane.showMessageDialog(this, "Debe diligenciar todo el formulario.", "Existen campos vacíos.", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            if (accesoBD.guardarAdministrador(admin)) {
                                exito = true;
                                mensaje = "Administrador creado con éxito.";
                            } else {
                                exito = false;
                                mensaje = "Ya el nombre de usuario existe o la cédula ya ha sido registrada para otro admin.";
                            }
                        }
                        break;
                    case 2:
                        if (JTxFCedula.getText().isEmpty()) {
                            JOptionPane.showMessageDialog(this, "Debe diligenciar la cédula del administrador.", "Existen campos vacíos.", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            //aquí llamaré al método para eliminar al admin
                            if (accesoBD.deleteAdmin(admin)) {
                                exito = true;
                                mensaje = "Administrador eliminado con éxito.";

                            } else {
                                exito = false;
                                mensaje = "Los datos del administrador no son correctos.";
                            }
                        }
                        break;
                    case 3:
                        if (JTxFCedula.getText().isEmpty()) {
                            JOptionPane.showMessageDialog(this, "Debe diligenciar la cédula del administrador.", "Existen campos vacíos.", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            //aquí llamaré al método para reingresar al administrador 
                            if (accesoBD.reingresarAdmin(admin)) {
                                exito = true;
                                mensaje = "Administrador reingresado con éxito.";
                            } else {
                                exito = false;
                                mensaje = "Los datos del administrador no son correctos.";
                            }
                        }
                        break;
                }

                if (exito) {

                    JOptionPane.showMessageDialog(this, mensaje, "Operación exitosa", JOptionPane.INFORMATION_MESSAGE);
                    vaciar(JPSU);
                    vaciar(JPNuevoAdmin);
                    this.setVisible(false);

                } else {

                    JOptionPane.showMessageDialog(this, mensaje, "Verificar", JOptionPane.ERROR_MESSAGE);

                }
            } else {
                JOptionPane.showMessageDialog(this, "Los datos del Super Usuario no son válidos. Verifique.", "Verificar.", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Las contraseñas del nuevo administrador no coinciden.", "Verificar.", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_JBAceptarActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        vaciar(JPSU);
        vaciar(JPNuevoAdmin);
        this.setVisible(false);
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JTxFCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxFCedulaKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_JTxFCedulaKeyTyped

    private void JTxFNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxFNombreKeyTyped
        char c = evt.getKeyChar();
        if (!(c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_JTxFNombreKeyTyped

    public boolean vacio(JPanel jpa) {
        for (int i = 0; i < jpa.getComponentCount(); i++) {
            if (jpa.getComponent(i) instanceof JTextField) {
                JTextField jt = (JTextField) jpa.getComponent(i);
                if (jt.getText().isEmpty()) {
                    return true;
                }
            } else {
                if (jpa.getComponent(i) instanceof JPasswordField) {
                    JPasswordField jp = (JPasswordField) jpa.getComponent(i);
                    if (jp.getText().isEmpty()) {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    public void enabled(boolean q) {
        JTxFNombre.setEnabled(q);
        JLNombre.setEnabled(q);
        JLUsuario.setEnabled(q);
        JTxFUsuario.setEnabled(q);
        JLPass.setEnabled(q);
        JTxFPass.setEnabled(q);
        JLConfiPass.setEnabled(q);
        JTxFConfiPass.setEnabled(q);
    }

    public void vaciar(JPanel jpa) {
        for (int i = 0; i < jpa.getComponentCount(); i++) {
            if (jpa.getComponent(i) instanceof JTextField) {
                JTextField jt = (JTextField) jpa.getComponent(i);
                jt.setText("");
            } else {
                if (jpa.getComponent(i) instanceof JPasswordField) {
                    JPasswordField jp = (JPasswordField) jpa.getComponent(i);
                    jp.setText("");
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAceptar;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JLabel JLCedula;
    private javax.swing.JLabel JLConfiPass;
    private javax.swing.JLabel JLNombre;
    private javax.swing.JLabel JLPass;
    private javax.swing.JLabel JLSUPass;
    private javax.swing.JLabel JLSUUsuario;
    private javax.swing.JLabel JLUsuario;
    private javax.swing.JPanel JPNuevoAdmin;
    private javax.swing.JPanel JPSU;
    private javax.swing.JTextField JTxFCedula;
    private javax.swing.JPasswordField JTxFConfiPass;
    private javax.swing.JTextField JTxFNombre;
    private javax.swing.JPasswordField JTxFPass;
    private javax.swing.JPasswordField JTxFSUPass;
    private javax.swing.JTextField JTxFSUUsuario;
    private javax.swing.JTextField JTxFUsuario;
    // End of variables declaration//GEN-END:variables
}
