/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import static Imagenes.ControlImagenes.DERECHA;
import static Imagenes.ControlImagenes.IZQUIERDA;
import javax.swing.JLabel;

/**
 *
 * @author Diego García
 */
public class Ganador extends javax.swing.JDialog {

    /**
     * Creates new form Ganador
     */
    public Ganador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
//        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
//        setBackground(new Color(0, 0, 0, 0));
//        setOpacity(0.6f);
//        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLNombreGanador = new javax.swing.JLabel();
        JLPremio = new javax.swing.JLabel();
        JL2 = new javax.swing.JLabel();
        JL1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLNombreGanador.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        JLNombreGanador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLNombreGanador.setText("dddd");
        getContentPane().add(JLNombreGanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 840, 60));

        JLPremio.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        JLPremio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLPremio.setText("qqqqq");
        getContentPane().add(JLPremio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 840, 70));
        getContentPane().add(JL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, -80, 423, 430));

        JL1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        getContentPane().add(JL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 360, 340));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 570, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getJLGanador() {
        return JLNombreGanador;
    }
    
    public void setJLGanador(JLabel JLGanador) {
        this.JLNombreGanador = JLGanador;
    }
    
    public JLabel getJLPremio() {
        return JLPremio;
    }
    
    public void setJLPremio(JLabel JLPremio) {
        this.JLPremio = JLPremio;
    }
    
    public void vista() {
        JL1.setIcon(IZQUIERDA);
        JL2.setIcon(DERECHA);
//        JLBomba.setIcon(BOMBA);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL1;
    private javax.swing.JLabel JL2;
    private javax.swing.JLabel JLNombreGanador;
    private javax.swing.JLabel JLPremio;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
