/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import static Logica.Mensajes.C_VALIDA;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import static java.awt.image.ImageObserver.WIDTH;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//import javax.swing.table.TableRowSorter;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Diego García
 */
public class ValorSorteo extends javax.swing.JDialog {

    /**
     * Creates new form ValorSorteo
     */
    private double valor, tipo, valorSorteo, valorConfirmacion;
    NumberFormat dispFormat = NumberFormat.getCurrencyInstance();
    NumberFormat editFormat = NumberFormat.getNumberInstance(Locale.ENGLISH);
    NumberFormatter dnFormat = new NumberFormatter(dispFormat);
    NumberFormatter enFormat = new NumberFormatter(editFormat);
    DefaultFormatterFactory currFactory = new DefaultFormatterFactory(dnFormat, dnFormat, enFormat);
    
    public ValorSorteo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Logo.png")).getImage());
        setResizable(false);
        setLocationRelativeTo(this);
        valor = tipo = 0;
        editFormat.setGroupingUsed(false);
        enFormat.setAllowsInvalid(true);
        JTxFValor.setFormatterFactory(currFactory);
        JTxFConfirmacion1.setFormatterFactory(currFactory);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        JLValor = new javax.swing.JLabel();
        JRBMayor = new javax.swing.JRadioButton();
        JRBMenor = new javax.swing.JRadioButton();
        JLConfirmacion = new javax.swing.JLabel();
        JTxFValor = new javax.swing.JFormattedTextField();
        JTxFConfirmacion1 = new javax.swing.JFormattedTextField();
        JBAceptar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        JLValores = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Datos del sorteo");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JLValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JLValor.setText("Valor del sorteo");

        buttonGroup1.add(JRBMayor);
        JRBMayor.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JRBMayor.setText("Sorteo Mayor");
        JRBMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBMayorActionPerformed(evt);
            }
        });
        JRBMayor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JRBMayorKeyPressed(evt);
            }
        });

        buttonGroup1.add(JRBMenor);
        JRBMenor.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JRBMenor.setText("Sorteo Menor");
        JRBMenor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JRBMenorKeyPressed(evt);
            }
        });

        JLConfirmacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JLConfirmacion.setText("Confirmación del valor");

        JTxFValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTxFValor.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        JTxFValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTxFValorFocusLost(evt);
            }
        });
        JTxFValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTxFValorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxFValorKeyTyped(evt);
            }
        });

        JTxFConfirmacion1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTxFConfirmacion1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        JTxFConfirmacion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTxFConfirmacion1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxFConfirmacion1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLValor, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JRBMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(JRBMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTxFValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTxFConfirmacion1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLValor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTxFValor)
                .addGap(30, 30, 30)
                .addComponent(JLConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JTxFConfirmacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRBMenor)
                    .addComponent(JRBMayor))
                .addContainerGap())
        );

        JBAceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JBAceptar.setText("Aceptar");
        JBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAceptarActionPerformed(evt);
            }
        });

        JBCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        JLValores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLValores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(451, 451, 451))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(JLValores, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JRBMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBMayorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBMayorActionPerformed

    private void JBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAceptarActionPerformed
        boolean error = true;
        
        try {
            if (valorSorteo <= 0 || JTxFValor.getText().isEmpty() || JTxFConfirmacion1.getText().isEmpty() || valorConfirmacion <= 0) {
                JOptionPane.showMessageDialog(this, C_VALIDA, "Monto de premio no válido", JOptionPane.ERROR_MESSAGE);
            } else {
                if (valorSorteo != valorConfirmacion) {
                    JOptionPane.showMessageDialog(this, "Las cantidades ingresadas no concuerdan.", "Cantidades deiferentes", JOptionPane.ERROR_MESSAGE);
                } else {
                    valor = valorSorteo;
                    if (JRBMenor.isSelected()) {
                        tipo = 0;
                        JTxFValor.setText("");
                        JTxFConfirmacion1.setText("");
                        dispose();
                    } else if (JRBMayor.isSelected()) {
                        tipo = 1;
                        JTxFValor.setText("");
                        JTxFConfirmacion1.setText("");
                        dispose();
                    } else {
                        error = true;
                        JOptionPane.showMessageDialog(this, "Debe seleccionar el tipo de premio.", "Criterios sin seleccionar", JOptionPane.ERROR_MESSAGE);
                        this.setVisible(true);
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, C_VALIDA, "Monto de premio no válido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JBAceptarActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        this.setVisible(false);
        valor = 0;
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JRBMayorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JRBMayorKeyPressed
        ActionEvent jd = new ActionEvent(evt, WIDTH, "Hola mundo");
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.JBAceptarActionPerformed(jd);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.JBCancelarActionPerformed(jd);
        }
    }//GEN-LAST:event_JRBMayorKeyPressed

    private void JRBMenorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JRBMenorKeyPressed
        ActionEvent jd = new ActionEvent(evt, WIDTH, "Hola mundo");
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.JBAceptarActionPerformed(jd);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.JBCancelarActionPerformed(jd);
        }
    }//GEN-LAST:event_JRBMenorKeyPressed

    private void JTxFValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxFValorKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        } else {
            
            JTxFValor.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) {
                    if (!JTxFValor.getText().isEmpty()) {
                        valorSorteo = Long.parseLong(JTxFValor.getText());
                    }
                }
            });
        }
    }//GEN-LAST:event_JTxFValorKeyTyped

    private void JTxFValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTxFValorFocusLost
//
//        JTxFValor.setFormatterFactory(currFactory);
//        System.out.println("sssojjskms");
    }//GEN-LAST:event_JTxFValorFocusLost

    private void JTxFValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxFValorKeyPressed

    }//GEN-LAST:event_JTxFValorKeyPressed

    private void JTxFConfirmacion1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxFConfirmacion1KeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        } else {
            JTxFConfirmacion1.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) {
                    valorConfirmacion = Long.parseLong(JTxFConfirmacion1.getText());
                }
            });
        }
    }//GEN-LAST:event_JTxFConfirmacion1KeyTyped

    private void JTxFConfirmacion1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxFConfirmacion1KeyPressed

    }//GEN-LAST:event_JTxFConfirmacion1KeyPressed
    
    public void visible(int numero, boolean prueba) {
        if (prueba) {
            JLValores.setText("Datos para el sorteo de prueba");
        } else {
            JLValores.setText("Valores para el sorteo número " + numero);
        }
        this.setVisible(true);
        JTxFValor.setText("");
        JTxFConfirmacion1.setText("");
        JRBMayor.setSelected(false);
        JRBMenor.setSelected(false);
    }
    
    public double[] valoresSorteo() {
        double[] valores = new double[2];
        valores[0] = valor;
        valores[1] = tipo;
        return valores;
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAceptar;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JLabel JLConfirmacion;
    private javax.swing.JLabel JLValor;
    private javax.swing.JLabel JLValores;
    private javax.swing.JRadioButton JRBMayor;
    private javax.swing.JRadioButton JRBMenor;
    private javax.swing.JFormattedTextField JTxFConfirmacion1;
    private javax.swing.JFormattedTextField JTxFValor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
