/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import static Logica.Mensajes.C_VALIDA;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego García
 */
public class ValorSorteo extends javax.swing.JDialog {

    /**
     * Creates new form ValorSorteo
     */
    private double valor, tipo;
    
    public ValorSorteo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
        valor = tipo = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        JLValor = new javax.swing.JLabel();
        JTxFValor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JRBMayor = new javax.swing.JRadioButton();
        JRBMenor = new javax.swing.JRadioButton();
        JTxFConfirmacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JLConfirmacion = new javax.swing.JLabel();
        JBAceptar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        JLValores = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Datos del sorteo");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JLValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JLValor.setText("Valor del sorteo");

        JTxFValor.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JTxFValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTxFValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTxFValorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxFValorKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("$");

        buttonGroup1.add(JRBMayor);
        JRBMayor.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JRBMayor.setText("Sorteo Mayor");
        JRBMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBMayorActionPerformed(evt);
            }
        });
        JRBMayor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JRBMayorKeyPressed(evt);
            }
        });

        buttonGroup1.add(JRBMenor);
        JRBMenor.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JRBMenor.setText("Sorteo Menor");
        JRBMenor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JRBMenorKeyPressed(evt);
            }
        });

        JTxFConfirmacion.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JTxFConfirmacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTxFConfirmacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTxFConfirmacionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxFConfirmacionKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("$");

        JLConfirmacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JLConfirmacion.setText("Confirmación del valor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTxFConfirmacion)
                            .addComponent(JTxFValor, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLValor, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(JRBMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(JRBMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLValor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTxFValor, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(JLConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTxFConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRBMenor)
                    .addComponent(JRBMayor))
                .addGap(30, 30, 30))
        );

        JBAceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JBAceptar.setText("Aceptar");
        JBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAceptarActionPerformed(evt);
            }
        });

        JBCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        JLValores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLValores, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(JBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JBAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JLValores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBAceptar)
                    .addComponent(JBCancelar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JRBMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBMayorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBMayorActionPerformed

    private void JBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAceptarActionPerformed
        boolean error = true;
        try {
            if (Double.parseDouble(JTxFValor.getText()) <= 0 || JTxFValor.getText().isEmpty() || JTxFConfirmacion.getText().isEmpty() || Double.parseDouble(JTxFConfirmacion.getText()) <= 0) {
                JOptionPane.showMessageDialog(this, C_VALIDA, "Monto de premio no válido", JOptionPane.ERROR_MESSAGE);
            } else {
                if (!JTxFValor.getText().equals(JTxFConfirmacion.getText())) {
                    JOptionPane.showMessageDialog(this, "Las cantidades ingresadas no concuerdan.", "Cantidades deiferentes", JOptionPane.ERROR_MESSAGE);
                } else {
                    valor = Double.parseDouble(JTxFValor.getText());
                    if (JRBMenor.isSelected()) {
                        tipo = 0;
                        this.setVisible(false);
                    } else if (JRBMayor.isSelected()) {
                        tipo = 1;
                        this.setVisible(false);
                    } else {
                        error = true;
                        JOptionPane.showMessageDialog(this, "Debe seleccionar el tipo de premio.", "Criterios sin seleccionar", JOptionPane.ERROR_MESSAGE);
                        this.setVisible(true);
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, C_VALIDA, "Monto de premio no válido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JBAceptarActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JTxFValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxFValorKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_JTxFValorKeyTyped

    private void JTxFValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxFValorKeyPressed
        ActionEvent jd = new ActionEvent(evt, WIDTH, "Hola mundo");
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.JBAceptarActionPerformed(jd);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.JBCancelarActionPerformed(jd);
        }
    }//GEN-LAST:event_JTxFValorKeyPressed

    private void JRBMayorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JRBMayorKeyPressed
        ActionEvent jd = new ActionEvent(evt, WIDTH, "Hola mundo");
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.JBAceptarActionPerformed(jd);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.JBCancelarActionPerformed(jd);
        }
    }//GEN-LAST:event_JRBMayorKeyPressed

    private void JRBMenorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JRBMenorKeyPressed
        ActionEvent jd = new ActionEvent(evt, WIDTH, "Hola mundo");
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.JBAceptarActionPerformed(jd);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.JBCancelarActionPerformed(jd);
        }
    }//GEN-LAST:event_JRBMenorKeyPressed

    private void JTxFConfirmacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxFConfirmacionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxFConfirmacionKeyPressed

    private void JTxFConfirmacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxFConfirmacionKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_JTxFConfirmacionKeyTyped
    
    public void visible(int numero) {
        JLValores.setText("Valores para el sorteo número " + numero);
        this.setVisible(true);
        JTxFValor.setText("");
        JTxFConfirmacion.setText("");
        JRBMayor.setSelected(false);
        JRBMenor.setSelected(false);
    }
    
    public double[] valoresSorteo() {
        double[] valores = new double[2];
        valores[0] = valor;
        valores[1] = tipo;
        return valores;
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAceptar;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JLabel JLConfirmacion;
    private javax.swing.JLabel JLValor;
    private javax.swing.JLabel JLValores;
    private javax.swing.JRadioButton JRBMayor;
    private javax.swing.JRadioButton JRBMenor;
    private javax.swing.JTextField JTxFConfirmacion;
    private javax.swing.JTextField JTxFValor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
