/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Administrador;
import static Modelo.BonoSolidario.administrador;
import Modelo.Peticiones;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author Diego García
 */
public class AddAdministrador extends javax.swing.JDialog {

    public int tipoOperacion;
    private Peticiones peticion;

    public AddAdministrador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Logo.png")).getImage());
        setResizable(false);
        setLocationRelativeTo(this);
        tipoOperacion = 0;
        peticion = new Peticiones();
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        JPFondo.setOpaque(false);
    }

    public int isTipoOperacion() {
        return tipoOperacion;
    }

    public void setTipoOperacion(int tipoOperacion) {
        this.tipoOperacion = tipoOperacion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPFondo = new javax.swing.JPanel();
        JTxFSUUsuario = new javax.swing.JTextField();
        JBAceptar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        JTxFSUPass = new javax.swing.JPasswordField();
        JTxFNombre = new javax.swing.JTextField();
        JTxFCedula = new javax.swing.JTextField();
        JTxFUsuario = new javax.swing.JTextField();
        JTxFPass = new javax.swing.JPasswordField();
        JTxFConfiPass = new javax.swing.JPasswordField();
        JTxFApellidos = new javax.swing.JTextField();
        JLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        JPFondo.add(JTxFSUUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 210, -1));

        JBAceptar.setBackground(new java.awt.Color(125, 202, 62));
        JBAceptar.setText("Aceptar");
        JBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAceptarActionPerformed(evt);
            }
        });
        JPFondo.add(JBAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 128, -1));

        JBCancelar.setBackground(new java.awt.Color(125, 202, 62));
        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });
        JPFondo.add(JBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 340, 130, -1));

        JTxFSUPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTxFSUPassKeyPressed(evt);
            }
        });
        JPFondo.add(JTxFSUPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 230, -1));

        JTxFNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxFNombreKeyTyped(evt);
            }
        });
        JPFondo.add(JTxFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 270, -1));

        JTxFCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxFCedulaKeyTyped(evt);
            }
        });
        JPFondo.add(JTxFCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 200, -1));
        JPFondo.add(JTxFUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 270, -1));
        JPFondo.add(JTxFPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 200, -1));
        JPFondo.add(JTxFConfiPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 200, -1));

        JTxFApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxFApellidosActionPerformed(evt);
            }
        });
        JPFondo.add(JTxFApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 270, -1));

        JLFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/addAdmin.jpg"))); // NOI18N
        JPFondo.add(JLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 370));

        getContentPane().add(JPFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAceptarActionPerformed
        if (new String(JTxFPass.getPassword()).equals(new String(JTxFConfiPass.getPassword()))) {
            //if (BonoSolidario.accesoBD.consultaAdmin(JTxFSUUsuario.getText(), JTxFSUPass.getText(), false)) {

            String password = DigestUtils.md5Hex(new String(JTxFSUPass.getPassword()));

            if (administrador.getTipo() == 1 && administrador.getUsuario().equals(JTxFSUUsuario.getText()) && administrador.getPass().equals(password)) {

                password = DigestUtils.md5Hex(new String(JTxFPass.getPassword()));
                Administrador admin;
                boolean exito = false;
                String mensaje = "";

                switch (tipoOperacion) {
                    case 1:
                        if (vacio()) {
                            JOptionPane.showMessageDialog(this, "Debe diligenciar todo el formulario.", "Existen campos vacíos.", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            admin = new Administrador(JTxFNombre.getText(), JTxFApellidos.getText(), Long.parseLong(JTxFCedula.getText()), password, JTxFUsuario.getText(), 0);
                            if (peticion.guardarAdministrador(admin)) {
                                exito = true;
                                mensaje = "Administrador creado con éxito.";
                            } else {
                                exito = false;
                                mensaje = "Ya el nombre de usuario existe o la cédula ya ha sido registrada para otro admin.";
                            }
                        }
                        break;
                    case 2:
                        if (JTxFCedula.getText().isEmpty()) {
                            JOptionPane.showMessageDialog(this, "Debe diligenciar la cédula del administrador.", "Existen campos vacíos.", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            //aquí llamaré al método para eliminar al admin
                            admin = new Administrador(JTxFNombre.getText(), JTxFApellidos.getText(), Long.parseLong(JTxFCedula.getText()), password, JTxFUsuario.getText(), 0);
                            if (peticion.deleteAdmin(admin)) {
                                exito = true;
                                mensaje = "Administrador eliminado con éxito.";

                            } else {
                                exito = false;
                                mensaje = "Los datos del administrador no son correctos.";
                            }
                        }
                        break;
                    case 3:
                        if (JTxFCedula.getText().isEmpty()) {
                            JOptionPane.showMessageDialog(this, "Debe diligenciar la cédula del administrador.", "Existen campos vacíos.", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            //aquí llamaré al método para reingresar al administrador 
                            admin = new Administrador(JTxFNombre.getText(), JTxFApellidos.getText(), Long.parseLong(JTxFCedula.getText()), password, JTxFUsuario.getText(), 0);
                            if (peticion.reingresarAdmin(admin)) {
                                exito = true;
                                mensaje = "Administrador reingresado con éxito.";
                            } else {
                                exito = false;
                                mensaje = "Los datos del administrador no son correctos.";
                            }
                        }
                        break;
                }

                if (exito) {

                    JOptionPane.showMessageDialog(this, mensaje, "Operación exitosa", JOptionPane.INFORMATION_MESSAGE);
                    vaciar();
                    dispose();

                } else if (!mensaje.isEmpty()) {

                    JOptionPane.showMessageDialog(this, mensaje, "Verificar", JOptionPane.ERROR_MESSAGE);

                }
            } else {
                JOptionPane.showMessageDialog(this, "Los datos del Super Usuario no son válidos. Verifique.", "Verificar.", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Las contraseñas del nuevo administrador no coinciden.", "Verificar.", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_JBAceptarActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        vaciar();
        dispose();
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JTxFCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxFCedulaKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_JTxFCedulaKeyTyped

    private void JTxFNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxFNombreKeyTyped
        char c = evt.getKeyChar();
        if (!(c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_JTxFNombreKeyTyped

    private void JTxFSUPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxFSUPassKeyPressed
        ActionEvent jd = new ActionEvent(evt, WIDTH, "Hola mundo");

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.JBAceptarActionPerformed(jd);
        }
    }//GEN-LAST:event_JTxFSUPassKeyPressed

    private void JTxFApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxFApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxFApellidosActionPerformed

    public boolean vacio() {
        for (int i = 0; i < JPFondo.getComponentCount(); i++) {
            if (JPFondo.getComponent(i) instanceof JTextField) {
                JTextField jt = (JTextField) JPFondo.getComponent(i);
                if (jt.getText().isEmpty()) {
                    return true;
                }

            } else if (JPFondo.getComponent(i) instanceof JPasswordField) {
                JPasswordField jt = (JPasswordField) JPFondo.getComponent(i);
                if (jt.getPassword().toString().isEmpty()) {
                    return true;
                }

            }
        }
        return false;
    }

    public void enabled(boolean q) {
        JTxFNombre.setEnabled(q);
        JTxFApellidos.setEnabled(q);
        JTxFUsuario.setEnabled(q);
        JTxFPass.setEnabled(q);
        JTxFConfiPass.setEnabled(q);
    }

    public void vaciar() {
        JTxFApellidos.setText("");
        JTxFCedula.setText("");
        JTxFConfiPass.setText("");
        JTxFNombre.setText("");
        JTxFPass.setText("");
        JTxFSUPass.setText("");
        JTxFSUUsuario.setText("");
        JTxFUsuario.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAceptar;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JLabel JLFondo;
    private javax.swing.JPanel JPFondo;
    private javax.swing.JTextField JTxFApellidos;
    private javax.swing.JTextField JTxFCedula;
    private javax.swing.JPasswordField JTxFConfiPass;
    private javax.swing.JTextField JTxFNombre;
    private javax.swing.JPasswordField JTxFPass;
    private javax.swing.JPasswordField JTxFSUPass;
    private javax.swing.JTextField JTxFSUUsuario;
    private javax.swing.JTextField JTxFUsuario;
    // End of variables declaration//GEN-END:variables
}
