/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JLabel;

/**
 *
 * @author Diego García
 */
public class Ganador extends javax.swing.JDialog {

    /**
     * Creates new form Ganador
     */
    public Ganador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
//        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
//        setBackground(new Color(0, 0, 0, 0));
//        setOpacity(0.6f);
//        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLNombreGanador = new javax.swing.JLabel();
        JLPremio = new javax.swing.JLabel();
        JLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLNombreGanador.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        JLNombreGanador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLNombreGanador.setText("Diego Armando García Altamiranda");
        getContentPane().add(JLNombreGanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 690, 70));

        JLPremio.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        JLPremio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLPremio.setText("$10.000.000,00");
        getContentPane().add(JLPremio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 600, 70));

        JLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ganador/Felicitaciones.gif"))); // NOI18N
        getContentPane().add(JLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getJLGanador() {
        return JLNombreGanador;
    }

    public void setJLGanador(JLabel JLGanador) {
        this.JLNombreGanador = JLGanador;
    }

    public JLabel getJLPremio() {
        return JLPremio;
    }

    public void setJLPremio(JLabel JLPremio) {
        this.JLPremio = JLPremio;
    }

//    public void vista() {
//        JL1.setIcon(IZQUIERDA);
//        JL2.setIcon(DERECHA);
//        JLBomba.setIcon(BOMBA);
//        System.out.println(JLFondo.getSize());
//        JLFondo.setIcon(new ImageIcon(GANADOR.getImage().getScaledInstance(JLFondo.getWidth(), JLFondo.getHeight(), Image.SCALE_DEFAULT)));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLFondo;
    private javax.swing.JLabel JLNombreGanador;
    private javax.swing.JLabel JLPremio;
    // End of variables declaration//GEN-END:variables
}
