/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import static Modelo.BonoSolidario.numerodeSorteos;
import static Modelo.Mensajes.COINCIDENCIA;
import static Modelo.Mensajes.I_SORTEO;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego García
 */
public class NumSorteos extends javax.swing.JDialog {

    public static int numsorteo2 = 0;

    public NumSorteos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Logo.png")).getImage());
        setLocationRelativeTo(this);
        System.out.println("Numero sorteos"+ this.getSize());
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTxFNumero = new javax.swing.JTextField();
        JTxFConfirmacion = new javax.swing.JTextField();
        JBAceptar = new javax.swing.JButton();
        JLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Datos de entrada para los sorteos del día de hoy");
        setPreferredSize(new java.awt.Dimension(496, 397));
        setResizable(false);
        getContentPane().setLayout(null);

        JTxFNumero.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        JTxFNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTxFNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxFNumeroActionPerformed(evt);
            }
        });
        JTxFNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTxFNumeroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxFNumeroKeyTyped(evt);
            }
        });
        getContentPane().add(JTxFNumero);
        JTxFNumero.setBounds(70, 100, 350, 50);

        JTxFConfirmacion.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        JTxFConfirmacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTxFConfirmacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxFConfirmacionActionPerformed(evt);
            }
        });
        JTxFConfirmacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTxFConfirmacionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxFConfirmacionKeyTyped(evt);
            }
        });
        getContentPane().add(JTxFConfirmacion);
        JTxFConfirmacion.setBounds(70, 230, 360, 50);

        JBAceptar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JBAceptar.setText("Aceptar");
        JBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(JBAceptar);
        JBAceptar.setBounds(160, 310, 170, 50);

        JLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/numSorteos.jpg"))); // NOI18N
        getContentPane().add(JLFondo);
        JLFondo.setBounds(0, 0, 500, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTxFNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxFNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxFNumeroActionPerformed

    private void JTxFNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxFNumeroKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_JTxFNumeroKeyTyped

    private void JBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAceptarActionPerformed
        if (JTxFNumero.getText().equals("") || JTxFConfirmacion.getText().equals("")) {
            JOptionPane.showMessageDialog(this, I_SORTEO, "Información importante!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int num1 = Integer.parseInt(JTxFNumero.getText());
            int num2 = Integer.parseInt(JTxFConfirmacion.getText());
            if (num1 == num2) {
                if (JOptionPane.showConfirmDialog(null, "Número de sorteos a realizar: " + num1 + ". \nDesea continuar?", "Confirmación de sorteos", JOptionPane.YES_NO_OPTION) == 0) {
                    numerodeSorteos = num1;
                    dispose();
                }
                JTxFNumero.setText("");
                JTxFConfirmacion.setText("");
            } else {
                JOptionPane.showMessageDialog(this, COINCIDENCIA, "No coinciden los campos", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_JBAceptarActionPerformed

    private void JTxFNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxFNumeroKeyPressed
        ActionEvent jd = new ActionEvent(evt, WIDTH, "Hola mundo");
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.JBAceptarActionPerformed(jd);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_JTxFNumeroKeyPressed

    private void JTxFConfirmacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxFConfirmacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxFConfirmacionActionPerformed

    private void JTxFConfirmacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxFConfirmacionKeyPressed
        ActionEvent jd = new ActionEvent(evt, WIDTH, "Hola mundo");

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.JBAceptarActionPerformed(jd);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            System.exit(0);
        }
    }//GEN-LAST:event_JTxFConfirmacionKeyPressed

    private void JTxFConfirmacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxFConfirmacionKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_JTxFConfirmacionKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAceptar;
    private javax.swing.JLabel JLFondo;
    private javax.swing.JTextField JTxFConfirmacion;
    private javax.swing.JTextField JTxFNumero;
    // End of variables declaration//GEN-END:variables
}
