/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import static Modelo.Mensajes.C_VALIDA;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import static java.awt.image.ImageObserver.WIDTH;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//import javax.swing.table.TableRowSorter;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Diego García
 */
public class ValorSorteo extends javax.swing.JDialog {

    /**
     * Creates new form ValorSorteo
     */
    private double valor, tipo, valorSorteo, valorConfirmacion;
    NumberFormat dispFormat = NumberFormat.getCurrencyInstance();
    NumberFormat editFormat = NumberFormat.getNumberInstance(Locale.ENGLISH);
    NumberFormatter dnFormat = new NumberFormatter(dispFormat);
    NumberFormatter enFormat = new NumberFormatter(editFormat);
    DefaultFormatterFactory currFactory = new DefaultFormatterFactory(dnFormat, dnFormat, enFormat);

    public ValorSorteo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Logo.png")).getImage());
        setResizable(false);
        setLocationRelativeTo(this);
        valor = tipo = 0;
        editFormat.setGroupingUsed(false);
        enFormat.setAllowsInvalid(true);
        JTxFValor.setFormatterFactory(currFactory);
        JTxFConfirmacion1.setFormatterFactory(currFactory);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        JBAceptar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        JLValores = new javax.swing.JLabel();
        JTxFConfirmacion1 = new javax.swing.JFormattedTextField();
        JRBMenor = new javax.swing.JRadioButton();
        JRBMayor = new javax.swing.JRadioButton();
        JTxFValor = new javax.swing.JFormattedTextField();
        JLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Datos del sorteo");
        setMinimumSize(new java.awt.Dimension(740, 522));
        setResizable(false);
        setSize(new java.awt.Dimension(740, 522));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBAceptar.setBackground(new java.awt.Color(125, 202, 62));
        JBAceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JBAceptar.setText("Aceptar");
        JBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(JBAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 170, 60));

        JBCancelar.setBackground(new java.awt.Color(125, 202, 62));
        JBCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(JBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 170, 60));

        JLValores.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(JLValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 9, 300, 40));

        JTxFConfirmacion1.setBorder(null);
        JTxFConfirmacion1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTxFConfirmacion1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        JTxFConfirmacion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTxFConfirmacion1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxFConfirmacion1KeyTyped(evt);
            }
        });
        getContentPane().add(JTxFConfirmacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 530, 90));

        buttonGroup1.add(JRBMenor);
        JRBMenor.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JRBMenor.setText("Sorteo Menor");
        JRBMenor.setBorder(null);
        JRBMenor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JRBMenorKeyPressed(evt);
            }
        });
        getContentPane().add(JRBMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 320, -1));

        buttonGroup1.add(JRBMayor);
        JRBMayor.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JRBMayor.setText("Sorteo Mayor");
        JRBMayor.setBorder(null);
        JRBMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBMayorActionPerformed(evt);
            }
        });
        JRBMayor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JRBMayorKeyPressed(evt);
            }
        });
        getContentPane().add(JRBMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 300, -1));

        JTxFValor.setBorder(null);
        JTxFValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTxFValor.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        JTxFValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTxFValorFocusLost(evt);
            }
        });
        JTxFValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTxFValorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxFValorKeyTyped(evt);
            }
        });
        getContentPane().add(JTxFValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 530, 90));

        JLFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/valorSorteo.jpg"))); // NOI18N
        getContentPane().add(JLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JRBMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBMayorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBMayorActionPerformed

    private void JBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAceptarActionPerformed
        boolean error = true;

        try {
            if (valorSorteo <= 0 || JTxFValor.getText().isEmpty() || JTxFConfirmacion1.getText().isEmpty() || valorConfirmacion <= 0) {
                JOptionPane.showMessageDialog(this, C_VALIDA, "Monto de premio no válido", JOptionPane.ERROR_MESSAGE);
            } else {
                if (valorSorteo != valorConfirmacion) {
                    JOptionPane.showMessageDialog(this, "Las cantidades ingresadas no concuerdan.", "Cantidades deiferentes", JOptionPane.ERROR_MESSAGE);
                } else {
                    valor = valorSorteo;
                    if (JRBMenor.isSelected()) {
                        tipo = 0;
                        JTxFValor.setText("");
                        JTxFConfirmacion1.setText("");
                        dispose();
                    } else if (JRBMayor.isSelected()) {
                        tipo = 1;
                        JTxFValor.setText("");
                        JTxFConfirmacion1.setText("");
                        dispose();
                    } else {
                        error = true;
                        JOptionPane.showMessageDialog(this, "Debe seleccionar el tipo de premio.", "Criterios sin seleccionar", JOptionPane.ERROR_MESSAGE);
                        this.setVisible(true);
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, C_VALIDA, "Monto de premio no válido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JBAceptarActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        this.setVisible(false);
        valor = 0;
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JRBMayorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JRBMayorKeyPressed
        ActionEvent jd = new ActionEvent(evt, WIDTH, "Hola mundo");
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.JBAceptarActionPerformed(jd);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.JBCancelarActionPerformed(jd);
        }
    }//GEN-LAST:event_JRBMayorKeyPressed

    private void JRBMenorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JRBMenorKeyPressed
        ActionEvent jd = new ActionEvent(evt, WIDTH, "Hola mundo");
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.JBAceptarActionPerformed(jd);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.JBCancelarActionPerformed(jd);
        }
    }//GEN-LAST:event_JRBMenorKeyPressed

    private void JTxFValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxFValorKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        } else {

            JTxFValor.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) {
                    if (!JTxFValor.getText().isEmpty()) {
                        valorSorteo = Long.parseLong(JTxFValor.getText());
                    }
                }
            });
        }
    }//GEN-LAST:event_JTxFValorKeyTyped

    private void JTxFValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTxFValorFocusLost
    }//GEN-LAST:event_JTxFValorFocusLost

    private void JTxFValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxFValorKeyPressed

    }//GEN-LAST:event_JTxFValorKeyPressed

    private void JTxFConfirmacion1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxFConfirmacion1KeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        } else {
            JTxFConfirmacion1.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) {
                    try {
                        valorConfirmacion = Long.parseLong(JTxFConfirmacion1.getText());
                    } catch (NumberFormatException x) {

                    }
                }
            });
        }
    }//GEN-LAST:event_JTxFConfirmacion1KeyTyped

    private void JTxFConfirmacion1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxFConfirmacion1KeyPressed

    }//GEN-LAST:event_JTxFConfirmacion1KeyPressed

    public void visible(int numero, boolean prueba) {
        if (prueba) {
            JLValores.setText("Datos para el sorteo de prueba");
        } else {
            JLValores.setText("Valores para el sorteo número " + numero);
        }
        this.setVisible(true);
        JTxFValor.setText("");
        JTxFConfirmacion1.setText("");
        JRBMayor.setSelected(false);
        JRBMenor.setSelected(false);
    }

    public double[] valoresSorteo() {
        double[] valores = new double[2];
        valores[0] = valor;
        valores[1] = tipo;
        return valores;
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAceptar;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JLabel JLFondo;
    private javax.swing.JLabel JLValores;
    private javax.swing.JRadioButton JRBMayor;
    private javax.swing.JRadioButton JRBMenor;
    private javax.swing.JFormattedTextField JTxFConfirmacion1;
    private javax.swing.JFormattedTextField JTxFValor;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
